apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: myapp
  namespace: dev
spec:
  interval: 1m
  chart:
    spec:
      chart: service-example
      version: "0.1.0"  
      sourceRef:
        kind: HelmRepository
        name: mirasys-chart
        namespace: flux-system
  values:
    app:
      image:
        repository: sepehrmdn/mirasys-assignment
        tag: "1.0.1"
      service:
        type: ClusterIP
        port: 9080
    mongodb:
      enabled: true
    redis:
      enabled: true
    nats:
      enabled: true
